### PR TITLE
Configuration through app.json

### PR DESCRIPTION
**Pull request by craziks-creator**
Error in configuration how to add env through  app.json
I have made a app.json and env inside this... What change should do in bot.py for that

### CODE REVIEW

**Review by AJAYK-01 — COMMENTED** [review]
Thanks for you PR @craziks-creator!. Did the deployment work for you when you tested? If not, could you provide what was the issue that came?

Also you don't necessarily have to host your own instance, you can use the public one from the description in your groups or as a DM.

**Comment by craziks-creator** [comment]
It works but I was doing through heroku deployment using env

**Comment by craziks-creator** [comment]
> Thanks for you PR @craziks-creator!. Did the deployment work for you when you tested? If not, could you provide what was the issue that came?
> 
> Also you don't necessarily have to host your own instance, you can use the public one from the description in your groups or as a DM.

 It works but I was doing through heroku deployment using env

**Comment by AJAYK-01** [comment]
> > Thanks for you PR @craziks-creator!. Did the deployment work for you when you tested? If not, could you provide what was the issue that came?
> > Also you don't necessarily have to host your own instance, you can use the public one from the description in your groups or as a DM.
> 
> It works but I was doing through heroku deployment using env

Could you try via the Heroku Button in your fork then?

**Comment by craziks-creator** [comment]
Yes I have tried 

Error in build: 


/tmp/pip-install-ha6f9zmq/h5py_91b9c71e25814a7988a4c19db6fb6bd3/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory
              27 | #include "hdf5.h"
                 |          ^~~~~~~~
           compilation terminated.

**Comment by craziks-creator** [comment]
> > > Thanks for you PR @craziks-creator!. Did the deployment work for you when you tested? If not, could you provide what was the issue that came?
> > > Also you don't necessarily have to host your own instance, you can use the public one from the description in your groups or as a DM.
> > 
> > 
> > It works but I was doing through heroku deployment using env
> 
> Could you try via the Heroku Button in your fork then?
/tmp/pip-install-ha6f9zmq/h5py_91b9c71e25814a7988a4c19db6fb6bd3/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory
              27 | #include "hdf5.h"
                 |          ^~~~~~~~
           compilation terminated.

**Comment by craziks-creator** [comment]
> > > Thanks for you PR @craziks-creator!. Did the deployment work for you when you tested? If not, could you provide what was the issue that came?
> > > Also you don't necessarily have to host your own instance, you can use the public one from the description in your groups or as a DM.
> > 
> > 
> > It works but I was doing through heroku deployment using env
> 
> Could you try via the Heroku Button in your fork then?

Here's new issue in build log: 
/tmp/pip-install-ha6f9zmq/h5py_91b9c71e25814a7988a4c19db6fb6bd3/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory
              27 | #include "hdf5.h"
                 |          ^~~~~~~~
           compilation terminated.

**Review by AJAYK-01 — COMMENTED** [review]
Closing this PR as the project has now been ported (#20) to Replit due to the free dyno removal by Heroku

**Pull request closed without merging**
